apiVersion: v1
kind: ConfigMap
metadata:
  name: insecure-config
data:
  # Insecure configurations for GhostOps testing
  database_host: "0.0.0.0"
  debug_mode: "true"
  
---
apiVersion: v1
kind: Service
metadata:
  name: public-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: vulnerable-app

---
# IAM Policy with overly permissive permissions
Resources:
  VulnerableRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: "*"
          Action: "sts:AssumeRole"
      Policies:
      - PolicyName: OverlyPermissivePolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"
